version: '3.4'

services:
  mynotes:
    image: ${DOCKER_REGISTRY-}mynotes
    build:
      context: .
      dockerfile: MyNotes/Dockerfile
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: my_notes
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - 5440:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
 postgres-data:
